name: Continuous Integration (CI)
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # lint:
  #   name: Lint
  #   uses: ./.github/workflows/lint.yml

  # sec:
  #   name: Sec
  #   uses: ./.github/workflows/sec.yml

  Cost:
    name: Cost
    uses: ./.github/workflows/cost.yml
    with:
      get_cloudflare_tfvars: true
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      KEYBASE_USER: ${{ secrets.KEYBASE_USER }}
      KEYBASE_PAPERKEY: ${{ secrets.KEYBASE_PAPERKEY }}