name: Continuous Integration (CI)
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  sec:
    name: Sec
    uses: ./.github/workflows/sec.yml
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  cost:
    name: Cost
    uses: ./.github/workflows/cost.yml
    # with:
      # get_cloudflare_tfvars: true
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      CLOUDFLARE_CONFIG: ${{ secrets.CLOUDFLARE_CONFIG }}
      # KEYBASE_USERNAME: ${{ secrets.KEYBASE_USERNAME }}
      # KEYBASE_PAPERKEY: ${{ secrets.KEYBASE_PAPERKEY }}

  terraform:
    name: Terraform
    uses: ./.github/workflows/terraform.yml
    secrets:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    #   GIT_SSH_KEY: ${{ secrets.GHA_BOT_SSH_KEY }}
    #   TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}