name: Quest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GA_PAT }}
    - name: Build and Publish  
      run: |
        docker build . --file Dockerfile --tag ghcr.io/jonfinley/rearc-quest:latest
        docker run ghcr.io/jonfinley/rearc-quest:latest
        docker push ghcr.io/jonfinley/rearc-quest:latest
     env: 
